# Generated by Django 4.2.7 on 2026-09-06 06:32

from django.db import migrations, models
import myauth.models


class Migration(migrations.Migration):

    dependencies = [
        ("myauth", "0003_profile_remove_orderitem_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=myauth.models.user_avatar_path,
                verbose_name="Аватар",
            ),
        ),
    ]
